HarelTech.WMS.App/Pages/Tasks/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HarelTech.WMS.App.Models;
using HarelTech.WMS.Common.Models;
using HarelTech.WMS.RestClient;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;

namespace HarelTech.WMS.App.Pages.Tasks
{
    public class IndexModel : PageModel
    {
        private readonly IWmsClient _wmsClient;
        private readonly IMemoryCache _cache;

        public IndexModel(IWmsClient wmsClient, IMemoryCache cache)
        {
            _wmsClient = wmsClient;
            _cache = cache;
        }
        [BindProperty]
        public string Company { get; set; }
        [BindProperty]
        public long WarhouseId { get; set; }
        [BindProperty]
        public EnumTaskType CurrnetTaskType { get; set; }
        
        public async Task<IActionResult> OnGetAsync(EnumTaskType taskType)
        {
            var userid = Utilities.UserId(User.Claims);
            Company = _cache.Get<string>($"{userid}_company");
            WarhouseId = _cache.Get<long>($"{userid}_warhouseId");
            CurrnetTaskType = taskType;
            
            var tasksTypes = await _wmsClient.GetTaskTypesAsync(Company);
            ViewData["PageTitle"] = tasksTypes.FirstOrDefault(w => w.HWMS_ITASKTYPE == (int)taskType).HWMS_ITASKTYPEDES + " Groups";
            


            return Page();
        }

        public async Task<IActionResult> OnGetGroupTasks(EnumTaskGroup taskGroup, EnumTaskType taskType)
        {
            var userid = Utilities.UserId(User.Claims);
            _cache.Set($"{userid}_taskGroup", taskGroup);
            return await Task.FromResult(ViewComponent("GroupTasksByType", new CompleteTasksByGroupRequest
            {
                Company = _cache.Get<string>($"{userid}_company"),
                TaskGroup = taskGroup,
                WarhouseId = _cache.Get<long>($"{userid}_warhouseId"),
                TaskType = taskType,
                UserId = userid
            }));
            

        }

      
    }
}

HarelTech.WMS.App/Pages/Tasks/TaskItems.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HarelTech.WMS.App.Models;
using HarelTech.WMS.Common.Models;
using HarelTech.WMS.RestClient;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;

namespace HarelTech.WMS.App.Pages.Tasks
{
    public class TaskItemsModel : PageModel
    {
        private readonly IWmsClient _wmsClient;
        private readonly IMemoryCache _cache;

        [BindProperty]
        public string Company { get; set; }
        [BindProperty]
        public long WarhouseId { get; set; }
        [BindProperty]
        public EnumTaskType CurrentTaskType { get; set; }
        [BindProperty]
        public List<CompleteTaskItem> CompleteTaskItems { get; set; }

        public TaskItemsModel(IWmsClient wmsClient, IMemoryCache cache)
        {
            _wmsClient = wmsClient;
            _cache = cache;
        }
        public async Task<IActionResult> OnGet(EnumTaskType taskType, string refOrderZone)
        {
            var userid = Utilities.UserId(User.Claims);
            Company = _cache.Get<string>($"{userid}_company");
            WarhouseId = _cache.Get<long>($"{userid}_warhouseId");
            CurrentTaskType = taskType;
            var taskGroup = _cache.Get<EnumTaskGroup>($"{userid}_taskGroup");
            _cache.Set($"{userid}_taskType", taskType);
            //var company = Request.Cookies["company"] ?? "smoukr";

            var tasksTypes = await _wmsClient.GetTaskTypesAsync(Company);
            ViewData["PageTitle"] = tasksTypes.FirstOrDefault(w => w.HWMS_ITASKTYPE == (int)taskType).HWMS_ITASKTYPEDES + " Tasks";

            CompleteTaskItems = await _wmsClient.GetCompleteTaskItems(new CompleteTaskItemsRequest
            {
                Company = Company,
                RefOrderOrZone = refOrderZone,
                TaskType = CurrentTaskType,
                TaskGroup = taskGroup,
                UserId = userid,
                WarhouseId = WarhouseId
            });
            CompleteTaskItems.ForEach(f => f.RefOrderOrZone = refOrderZone);
            _cache.Set($"{userid}_CompleteTaskItems", CompleteTaskItems);
            return await Task.FromResult(Page());
        }

        public async Task<IActionResult> OnGetTaskTransaction(long part)
        {
            var userid = Utilities.UserId(User.Claims);
            CompleteTaskItems = _cache.Get<List<CompleteTaskItem>>($"{userid}_CompleteTaskItems");
            var taskItem = CompleteTaskItems.FirstOrDefault(w => w.PART == part);

            return await Task.FromResult(RedirectToPage("Transaction", taskItem));
        }
    }
}

HarelTech.WMS.App/Pages/Tasks/Transaction.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using HarelTech.WMS.App.Models;
using HarelTech.WMS.Common.Models;
using HarelTech.WMS.RestClient;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Serilog;

namespace HarelTech.WMS.App.Pages.Tasks
{
    public class TransactionModel : PageModel
    {
        private readonly IWmsClient _wmsClient;
        private readonly IMemoryCache _cache;

        [BindProperty]
        public string Company { get; set; }
        [BindProperty]
        public long WarhouseId { get; set; }
        [BindProperty]
        public EnumTaskType CurrentTaskType { get; set; }
        [BindProperty]
        public CompleteTaskItem TaskItem { get; set; }
        [BindProperty]
        public List<TaskLotSerial> TaskLot { get; set; }
        [BindProperty]
        public bool DisplayFromBin { get; set; }
        [BindProperty]
        public bool ChangeFromBin { get; set; }
        [BindProperty]
        public bool DisplayToBin { get; set; }
        [BindProperty]
        public bool ChangeToBin { get; set; }
        [BindProperty]
        public  List<ITaskLotModel> OpenedTaskLots { get; set; }
        public string UserName;
        public string Password;
        public string TaskLotJson { get; set; }
        public TransactionModel(IWmsClient wmsClient, IMemoryCache cache)
        {
            _wmsClient = wmsClient;
            _cache = cache;
        }
        public async Task<IActionResult> OnGet(CompleteTaskItem taskItem)
        {
            var userid = Utilities.UserId(User.Claims);
            Company = _cache.Get<string>($"{userid}_company");
            WarhouseId = _cache.Get<long>($"{userid}_warhouseId");
            CurrentTaskType = _cache.Get<EnumTaskType>($"{userid}_taskType");
            TaskItem = taskItem;
            UserName = Utilities.UserLogin(User.Claims);
            Password = Utilities.Password(User.Claims);

            var tasksTypes = await _wmsClient.GetTaskTypesAsync(Company);
            ViewData["PageTitle"] = tasksTypes.FirstOrDefault(w => w.HWMS_ITASKTYPE == (int)CurrentTaskType).HWMS_ITASKTYPEDES + " Transaction";
            OpenedTaskLots = new List<ITaskLotModel>();
            if (CurrentTaskType != EnumTaskType.Receive)
            {
                TaskLot = await _wmsClient.GetTransactionItems(new TransactionItemsRequest
                {
                    Company = Company,
                    ParId = taskItem.PART,
                    WarhouseId = WarhouseId
                });

                OpenedTaskLots = await _wmsClient.GetOpenedTaskLots(Company, taskItem.HWMS_ITASK);
            }
            else
                TaskLot = new List<TaskLotSerial>();

            if (TaskLot != null && TaskLot.Count >= 0)
            {
                await _wmsClient.ActivateTask(new ActivateTaskRequest
                {
                    Company = Company,
                    TaskId = taskItem.HWMS_ITASK,
                    UserId = userid
                });

                List<TaskLotSerial> selectedLot=null;
                if (CurrentTaskType != EnumTaskType.Receive)
                {
                    selectedLot = TaskLot.Where(w => w.FROMBIN == TaskItem.HWMS_ITASKFROMBIN).ToList();
                }
                else
                {
                    selectedLot = TaskLot.Where(w => w.TOBIN == TaskItem.HWMS_ITASKTOBIN).ToList();
                }
                if (selectedLot != null)
                {
                    var ids = selectedLot.Select(s => s.HWMS_ITASK).ToList();
                    TaskLot.RemoveAll(w =>  ids.Contains(w.HWMS_ITASK));
                    TaskLot.InsertRange(0, selectedLot);
                }
            }
            

            switch (CurrentTaskType)
            {
                case EnumTaskType.Pick:
                    DisplayFromBin = true; ChangeFromBin = false; DisplayToBin = true; ChangeToBin = true;
                    break;
                case EnumTaskType.Ship:
                    DisplayFromBin = true; ChangeFromBin = false; DisplayToBin = false; ChangeToBin = false;
                    break;
                case EnumTaskType.Receive:
                    DisplayFromBin = false; ChangeFromBin = false; DisplayToBin = true; ChangeToBin = true;
                    break;
                case EnumTaskType.Store:
                    DisplayFromBin = true; ChangeFromBin = false; DisplayToBin = true; ChangeToBin = true;
                    break;
                case EnumTaskType.Transfer:
                    DisplayFromBin = true; ChangeFromBin = false; DisplayToBin = true; ChangeToBin = true;
                    break;
                default:
                    break;
            }

            TaskLotJson = JsonSerializer.Serialize(TaskLot, new JsonSerializerOptions() { WriteIndented=false, AllowTrailingCommas =true });
            return Page();
        }

        public async Task<IActionResult> OnPostAddTaskLots([FromBody]List<TaskLotSerial> taskLots)
        {
            try
            {
                var userid = Utilities.UserId(User.Claims);
                if (taskLots.Any() && taskLots[0].Serials == null)
                {
                    var result = await _wmsClient.AddTaskLots(new AddTaskLotsRequest
                    {
                        Company = _cache.Get<string>($"{userid}_company"),
                        Lots = taskLots
                    });
                    return new JsonResult(new { Success = result });
                }

                //serials
                var taskLotId = await _wmsClient.AddTaskLot(new AddTaskLotsRequest
                {
                    Company = _cache.Get<string>($"{userid}_company"),
                    Lots = taskLots
                });

                return new JsonResult(new { taskLotId });

            }
            catch (System.Exception ex)
            {
                Log.Error(ex, "OnPostAddTaskLots");
                return new JsonResult(new { Success = false });
            }
            

            
        }

        public async Task<IActionResult> OnGetBins()
        {
            var userid = Utilities.UserId(User.Claims);
            Company = _cache.Get<string>($"{userid}_company");
            WarhouseId = _cache.Get<long>($"{userid}_warhouseId");

            return await Task.FromResult( ViewComponent("Bins", new { company = Company, warhouseId = WarhouseId }));

        }

        public async Task<IActionResult> OnGetSerials(long partId, long lot, long iTaskLot ,string locName="")
        {
            var userid = Utilities.UserId(User.Claims);
            Company = _cache.Get<string>($"{userid}_company");
            return await Task.FromResult(ViewComponent("Serials", new { company = Company, partId, lot, locName, iTaskLot }));
        }

        public async Task<IActionResult> OnDeleteTaskLots(long taskId)
        {
            var userid = Utilities.UserId(User.Claims);
            Company = _cache.Get<string>($"{userid}_company");
            var result = await _wmsClient.DeleteTaskLots(Company, taskId);
            return new JsonResult(new { Success = true, result });
        }

        public async Task<IActionResult> OnGetAddNewSerialCard(int id, string serialNumber)
        {
            ViewData["Id"] = id;
            ViewData["SerialNumber"] = serialNumber;

            return await Task.FromResult(new PartialViewResult
            {
                ViewName = "_newSerialCard",
                ViewData = ViewData
            });
        }

        public async Task<IActionResult> OnPostAddNewLot([FromBody]AddNewLotRequest request)
        {
            request.LotNumber = request.LotNumber == "" ? "0" : request.LotNumber;
            return await Task.FromResult(Partial("_newLotCard", request));
        }

        public async Task<IActionResult> OnGetDeleteOpenTaskSerials(long taskLot)
        {
            var userid = Utilities.UserId(User.Claims);
            Company = _cache.Get<string>($"{userid}_company");
            var result = await _wmsClient.DeleteOpenedTaskLotSerials(Company, taskLot);
                return new JsonResult(new { Success = result });
        }
    }
}

HarelTech.WMS.App/Pages/Tasks/Index.cshtml
@page  
@model HarelTech.WMS.App.Pages.Tasks.IndexModel
@{
    ViewData["Title"] = "Task Type";
}

@Html.AntiForgeryToken()
    <input type="hidden" id="task_type" value="@Model.CurrnetTaskType" />
    <div class="animated fadeIn fast" style="margin-top:20px;">
        <div class="text-center">
            <h5 class="text-center">GROUP TASKS BY</h5>
        </div>
        <div class="col-12 col-md-8 col-lg-4">
            <div class="btn-group w-100" data-toggle="buttons">
                <label class="btn btn-white form-check-label active">
                    <input class="form-check-input" type="radio" name="options" id="option1" autocomplete="off" checked onclick="change_search_placeholder('Search Reference')">
                    Order / Doc #
                </label>
                <label class="btn btn-white form-check-label">
                    <input class="form-check-input" type="radio" name="options" id="option2" autocomplete="off" onclick="change_search_placeholder('Search Zone')"> Zone #
                </label>
            </div>
        </div>
        
        <!-- Search-->
        <div class="form-inline d-flex justify-content-center md-form form-sm active-cyan-2 mt-4">
            <input id="search_group" class="form-control form-control-sm mr-2 w-75" type="text" placeholder="Search Order/Doc"
                   aria-label="Search" onkeyup="search_on_list();" autofocus autocomplete="off">
            <i class="fas fa-search" aria-hidden="true" onclick="search_on_list();"></i>
        </div>

        <div id="group_tasks">
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $("#btn_menu").hide();
        $("#btn_back").attr("href", app.url + "/Index");
        $("#btn_back").show();
        get_group_Tasks(1);

    });

    function get_group_Tasks(taskGroup) {
        var taskType = $("#task_type").val();
        $.get(app.url + "/Tasks/?handler=GroupTasks&taskGroup=" + taskGroup + "&taskType=" + taskType, function (data) {
            $("#group_tasks").html(data).addClass('animated fadeInDown');
        });
    }

    function change_search_placeholder(val) {
        if (val.includes("Reference"))
            get_group_Tasks(1);
        else
            get_group_Tasks(2);
        $("#search_group").attr("placeholder", val).fadeIn(500);
    }

    function search_on_list() {

        var input = document.getElementById("search_group");
        var filter = input.value;
        var nodes = $("#group_tasks .card");

        for (i = 0; i < nodes.length; i++) {
            if (!filter || filter === '') {
                nodes[i].style.display = "block";
                continue;
            }
            if (nodes[i].innerText.includes(filter)) {
                nodes[i].style.display = "block";
            } else {
                nodes[i].style.display = "none";
            }
        }

    }
    </script>

HarelTech.WMS.App/Pages/Tasks/TaskItems.cshtml
@page
@model HarelTech.WMS.App.Pages.Tasks.TaskItemsModel
@{
    ViewData["Title"] = "Task Items";
    var curType = (int)Model.CurrentTaskType;
}
@Html.AntiForgeryToken()
<input type="hidden" id="task_type" value="@Model.CurrentTaskType" />
<div class="animated fadeIn faster" style="margin-top:20px;">
    <div class="text-center">
        <h5 class="text-center">TASKS BY</h5>
    </div>
    <div class="col-12 col-md-8 col-lg-4">
        <div class="btn-group w-100" data-toggle="buttons">
            <label class="btn btn-white form-check-label active">
                <input class="form-check-input" type="radio" name="options" id="option1" autocomplete="off" checked onclick="order_by('Bin')">
                Bin #
            </label>
            <label class="btn btn-white form-check-label">
                <input class="form-check-input" type="radio" name="options" id="option2" autocomplete="off" onclick="order_by('Part')"> Part #
            </label>
        </div>
    </div>

    <!-- Search-->
    <div class="form-inline d-flex justify-content-center md-form form-sm active-cyan-2 mt-4">
        <input id="search_group" class="form-control form-control-sm mr-2 w-75" type="text" placeholder="Search Bin"
               aria-label="Search Bin" onkeyup="search_on_list();" autofocus autocomplete="off">
        <i class="fas fa-search" aria-hidden="true"></i>
    </div>
</div>

<div id="task_item_list" class="animated fadeInDown">
    @foreach (var item in Model.CompleteTaskItems)
    {
        var bin = curType != 3 ? item.HWMS_ITASKFROMBIN:item.HWMS_ITASKTOBIN;
        <div class="card promoting-card m-3">
            <div class="tcube card-body d-flex flex-row">
                @if (item.CompletedTasks == 0)
                {
                    <span class="col-4 text-center" style="background-color: #9EADB9; color: white;font-family: Montserrat !important; font-weight: 500;font-size:large">
                        <i class="fas fa-pencil-alt mt-4" style="color: white !important;"></i>
                        <br /> @item.CompletedTasks/@item.TotalTasks
                    </span>
                }
                else if (item.CompletedTasks < item.TotalTasks)
                {
                    <span class="col-4 text-center" style="background-color: #FFD2D5; color: white;font-family: Montserrat !important; font-weight: 500;font-size:large">
                        <i class="fas fa-pencil-alt mt-4" style="color: white !important;"></i>
                        <br /> @item.CompletedTasks/@item.TotalTasks
                    </span>
                }
                else
                {
                    <span class="col-4 text-center" style="background-color: #3DBFD9; color: white;font-family: Montserrat !important; font-weight: 500;font-size:large">
                        <i class="fas fa-pencil-alt mt-4" style="color: white !important;"></i>
                        <br /> @item.CompletedTasks/@item.TotalTasks
                    </span>
                }
            <div class="col-8 mt-1">
                <!-- Title -->
                @*<a href="/Tasks/TaskItems/TaskTransaction?part=@item.PART"><h6 class="card-title font-weight-bold mb-2" style="font-family: Montserrat !important;">@item.PARTDES</h6><i class="fa fa-chevron-right float-right" aria-hidden="true"></i></a>*@
                <h6 class="card-title font-weight-bold mb-2" style="font-family: Montserrat !important;">@item.PARTDES</h6>
                @if (item.CompletedTasks < item.TotalTasks)
                {
                <a asp-page-handler="TaskTransaction" asp-route-part="@item.PART">
                    <p class="part card-text">Part #: @item.PARTNAME <i class="fa fa-chevron-right float-right" aria-hidden="true"></i></p></a>
                }
                else
                {
                    <p class="part card-text">Part #: @item.PARTNAME </p>
                }
            <span class="card-text" style="background-color: #E9F5FF;">@item.HWMS_REFTYPENAME: @item.HWMS_REFORDER</span>
                <br />
                <i class="fab fa-periscope prefix" style="color: #3DBFD9"></i> <span class="bin card-text">@bin</span>
                
                
            </div>
            </div>
        </div>
    }
</div>

<script>
    var search_subject = "Bin";
    $(document).ready(function () {
        $("#btn_menu").hide();
        $("#btn_back").attr("href", app.url + "/Tasks/Index?taskType=@curType");
        $("#btn_back").show();
        //get_group_Tasks(1);
    });

    function order_by(val) {
        search_subject = val;
        if (val === "Bin")
            $("#search_group").attr("placeholder", "Search Bin").fadeIn(500);
        else
            $("#search_group").attr("placeholder", "Search Part").fadeIn(500);
    }

    function search_on_list() {

        var input = document.getElementById("search_group");
        var filter = input.value.toLowerCase();
        var nodes = $("#task_item_list .card");
        var inodes;
        if (search_subject === "Bin")
            inodes = $("#task_item_list .bin");
        else
            inodes = $("#task_item_list .part");

        for (i = 0; i < nodes.length; i++) {
            if (!filter || filter === '') {
                nodes[i].style.display = "block";
                continue;
            }

            if (inodes[i].innerText.toLowerCase().includes(filter)) {
                nodes[i].style.display = "block";
            } else {
                nodes[i].style.display = "none";
            }
        }

    }
</script>

HarelTech.WMS.App/Pages/Tasks/_modalConfirmCompleteTask.cshtml
<div class="modal fade" id="modalConfirmCompleteTask" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true" style="font-weight: 700 !important;">
    <div class="modal-dialog modal-sm modal-notify modal-info modal-dialog-centered" role="document">
        <!--Content-->
        <div class="modal-content text-center">
            <!--Header-->
            <div class="modal-header d-flex justify-content-center">
                <p class="heading">Are you sure?</p>
            </div>

            <!--Body-->
            <div class="modal-body">
                <p id="p_message">Task will be completed and closed</p>
            </div>

            <!--Footer-->
            <div class="modal-footer flex-center">
                <a href="#" onclick="finalize_task('c');" class="btn  btn-outline-info waves-effect">Yes</a>
                <a type="button" class="btn  btn-danger waves-effect" data-dismiss="modal">No</a>
            </div>
        </div>
        <!--/.Content-->
    </div>
</div>

HarelTech.WMS.App/Pages/Tasks/_modalConfirmPartialCompleteTask.cshtml
<div class="modal fade" id="modalConfirmPartialCompleteTask" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true" style="font-weight: 700 !important;">
    <div class="modal-dialog modal-sm modal-notify modal-danger modal-dialog-centered" role="document">
        <!--Content-->
        <div class="modal-content text-center">
            <!--Header-->
            <div class="modal-header d-flex justify-content-center">
                <p class="heading">Are you sure?</p>
            </div>

            <!--Body-->
            <div class="modal-body">
                <p id="p_message">Task will be completed and closed with missing quantitys:</p>
                <p>Total Required: @Model.TaskItem.TotalTasks</p>
                <p>Total Reported: <span id="total_reported"></span></p>
            </div>

            <!--Footer-->
            <div class="modal-footer flex-center">
                <a href="#" onclick="finalize_task('p');" class="btn  btn-outline-danger">Yes</a>
                <a type="button" class="btn  btn-danger waves-effect" data-dismiss="modal">No</a>
            </div>
        </div>
        <!--/.Content-->
    </div>
</div>

HarelTech.WMS.App/Pages/Tasks/_newLotCard.cshtml
@model HarelTech.WMS.Common.Models.AddNewLotRequest
@{
    var i = Model.Id;
    var sernflag = Model.SernFlag;
    var qtyDisabled = string.IsNullOrEmpty(Model.SernFlag) ? "":"disabled";
    var partId = Model.PartId;
    var curType = Model.TaskType;
}
<div id="card_@i" class="card m-2 animated fadeInDown" data-taskid="@Model.TaskId" data-lot="0" data-lotnumber="@Model.LotNumber">
    <a onclick="remove_bin_card('card_@i');" class="btn-floating btn-action ml-auto mr-1" style="background-color:white;">    <i class="fas fa-minus" style="background-color: white;"></i></a>
    <div class="card-body m-2">
        <div class="md-form input-group mb-3" style="font-weight: 700 !important">
            <div class="input-group-prepend">
                <span class="input-group-text md-addon" id="material-addon1">Lot #:</span>
            </div>
            <input type="text" class="form-control" id="lot_number_@i" value="@Model.LotNumber" onchange="update_lotnumber(@i);"
                   aria-describedby="material-addon1" style="color: #3DBFD9;" required>
        </div>

        <div class="md-form input-group mb-3" style="font-weight: 700 !important">
            <div class="input-group-prepend">
                <span class="input-group-text md-addon" id="material-addon2">Status: </span>
            </div>
            <div class="col mt-1" id="status_@i" aria-describedby="material-addon2">Goods</div>
        </div>
        <div class="md-form input-group mb-3" style="font-weight: 700 !important">
            <div class="input-group-prepend">
                <span class="input-group-text md-addon" id="material-addon3">Exp: </span>
            </div>
            <div class="col mt-2" aria-describedby="material-addon3">
                <div class="md-form md-outline input-with-post-icon datepicker">
                    <input placeholder="Select date" type="text" id="exp_date_@i" class="form-control" value="@DateTime.Now.AddYears(1).ToString("dd/MM/yyyy")">
                    <i class="fas fa-calendar input-prefix" tabindex=0></i>
                </div>
            </div>
        </div>
        <hr />

        <div class="md-form input-group mb-3" style="font-weight: 600 !important;background-color: #E9F5FF;">
            <div class="input-group-prepend">
                <span class="input-group-text md-addon" id="material-addon4">To Bin/Area: </span>
            </div>
            <div class="col" id="tobin_@i" aria-describedby="material-addon4">
                <input class="form-control" id="span_tobin_@i" value="@Model.ToBin" disabled />
            </div>
            <a data-toggle="modal" data-target="#binsModalPreview" data-spanid="span_tobin_@i">
                <div class="input-group-append mt-2">
                    <i class="fas fa-arrow-right float-right"></i>
                </div>
            </a>
        </div>

        <div class="row text-center mt-4">
            <div class="col-4" style="font-weight: 600 !important;">Quantity:</div>
            <div class="col-8">
                <div class="def-number-input number-input safari_only" style="background-color:#3DBFD9;">
                    <button onclick="minusQty('qty_@i');" class="minus"></button>
                    <input id="qty_@i" class="quantity" min="1" name="quantity" value="0" type="number" onchange="update_total_tasks();" required @qtyDisabled>
                    <button onclick="plusQty('qty_@i');" class="plus"></button>
                </div>
            </div>
        </div>
        @if (sernflag != "")
        {
            var bin = curType != 3 ? Model.FromBin : "";
            <div class="row mr-2 ml-2">
                <a data-toggle="modal" data-target="#serialsModalPreview" data-card="#card_@i"
                   data-lot="@Model.LotNumber" data-partid="@partId"
                   data-locname="@bin" data-serial="0"
                   class="btn btn-outline-cyan btn-block mt-2" style="color: #3DBFD9;border-color: #3DBFD9 !important">Add Serial numbers <i class="fas fa-arrow-right float-right"></i></a>
            </div>
        }
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.datepicker').datepicker({
            format: 'dd/mm/yyyy',
        });
    });

    function update_lotnumber(i) {
        $("#task_lots #card_" + i).data("lotnumber", $("#task_lots #lot_number_" + i).val());
    }

</script>

<style>
    .md-form {
        margin-top: 0px !important;
    }
    .md-form.input-group .input-group-text.md-addon {
        font-weight: 700;
    }
</style>

HarelTech.WMS.App/Pages/Tasks/_newSerialCard.cshtml
@{ 
    var id = ViewData["Id"];
    var serialNumber = ViewData["SerialNumber"];
}
<div id="serial_card_@id" class="tcube card promoting-card m-3" data-serial="0" data-serialno="@serialNumber">
    <!-- Card content -->
    <div class="card-body d-flex flex-row">
        <!-- Content -->
        <div class="w-100">
            <!-- Title -->
            <h5>Serial #: <span id="span_serial_number">@serialNumber</span></h5>
            <h5>Status  : Goods</h5>
            <div class="form-check checkbox-teal mb-2 p-0">
                <input type="checkbox" class="form-check-input" id="chk_@id"
                       onchange="change_serial_selection('#serial_card_@id', true);" checked>
                <label class="form-check-label" for="chk_@id">Add Serial</label>
            </div>
        </div>
    </div>
</div>