HarelTech.WMS.App/Pages/Account/Company.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HarelTech.WMS.App.Models;
using HarelTech.WMS.Common.Models;
using HarelTech.WMS.RestClient;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;

namespace HarelTech.WMS.App
{
    public class CompanyModel : PageModel
    {
        private readonly IWmsClient _wmsClient;
        private readonly IMemoryCache _cache;
        [BindProperty]
        public string Company { get; set; }
        [BindProperty]
        public long Warhouse { get; set; }
        
        public CompanyModel(IWmsClient wmsClient, IMemoryCache cache)
        {
            _wmsClient = wmsClient;
            _cache = cache;
        }
        public async Task<IActionResult> OnGet(string companies)
        {
            var cmps =  System.Text.Json.JsonSerializer.Deserialize<List<Company>>(companies);
            //cmps.Insert(0, new Common.Models.Company { dname = "", title = "Select" });

            ViewData["Companies"] = new SelectList(cmps, "dname", "title");
            var wrhs = await _wmsClient.GetUserWarhousesAsync(cmps[0].dname, Utilities.UserId(User.Claims));

            ViewData["Warhouses"] = new SelectList(wrhs.OrderByDescending(o => o.IsDefault), "warhs", "warhsdes");
            _cache.Set($"{Utilities.UserId(User.Claims)}_companies", companies, DateTime.Now.AddHours(8));
            return await Task.FromResult(Page());
        }

        public async Task<IActionResult> OnGetWarhouses(string company)
        {
            var wrhs = await _wmsClient.GetUserWarhousesAsync(company, Utilities.UserId(User.Claims));

            return new JsonResult(new { success = true, warhouses = wrhs.OrderByDescending(o => o.IsDefault) });
        }

        public async Task<IActionResult> OnPostAsync()
        {
            _cache.Set($"{Utilities.UserId(User.Claims)}_company", Company);
            _cache.Set($"{Utilities.UserId(User.Claims)}_warhouseId", Warhouse);
            _cache.Set($"{Utilities.UserId(User.Claims)}_companyName", Request.Form["CompanyName"].ToString());
            _cache.Set($"{Utilities.UserId(User.Claims)}_warhouseName", Request.Form["WarhouseName"].ToString());
            return await Task.FromResult(RedirectToPage("../Index"));
        }

        public async Task<IActionResult> OnGetCompanies()
        {
            var companies = _cache.Get<string>($"{Utilities.UserId(User.Claims)}_companies");
            return await Task.FromResult(RedirectToAction("OnGet", new { companies }));
        }
    }
}

HarelTech.WMS.App/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using HarelTech.WMS.Common.Models;
using HarelTech.WMS.RestClient;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HarelTech.WMS.App.Pages
{
    public class LoginModel : PageModel
    {
        private readonly IWmsClient _wmsClient;
        //private readonly IMemoryCache _cache;

        [BindProperty]
        public UserLoginModel UserLogin { get; set; }
        public LoginModel(IWmsClient wmsClient)
        {
            _wmsClient = wmsClient;
            //_cache = cache;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost()
        {
            var user = await _wmsClient.GetSystemUserAsync(UserLogin);

            if (user.Id == 0)
                return RedirectToPage("ErrorLogin", new { error = user.Response.Error });


            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, UserLogin.UserName),
                new Claim(ClaimTypes.Name, user.USERNAME),
                //new Claim(ClaimTypes.Email, "test@gmail.com"),
                new Claim(ClaimTypes.UserData, user.Id.ToString()),
                new Claim(ClaimTypes.Sid , UserLogin.Password),
                new Claim(ClaimTypes.Role, "User"),
            };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                // Refreshing the authentication session should be allowed.

                ExpiresUtc = DateTimeOffset.UtcNow.AddHours(12),
                // The time at which the authentication ticket expires. A 
                // value set here overrides the ExpireTimeSpan option of 
                // CookieAuthenticationOptions set with AddCookie.

                IsPersistent = true,
                // Whether the authentication session is persisted across 
                // multiple requests. When used with cookies, controls
                // whether the cookie's lifetime is absolute (matching the
                // lifetime of the authentication ticket) or session-based.

                IssuedUtc = DateTime.Now,
                // The time at which the authentication ticket was issued.

                RedirectUri = "/Account/Login"
                // The full path or absolute URI to be used as an http 
                // redirect response value.
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);

            //make login to license service, if ok, go on
            return RedirectToPage("Company", new { companies = UserLogin.Companies });
            //return new JsonResult(new { success = true, message = "" });
        }

        public async Task<IActionResult> OnGetLogout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("Login");
        }
    }
}

HarelTech.WMS.App/Pages/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="manifest" href="~/manifest.json" />
    <meta name="mobile-web-app-capable" content="yes">
    <title>@ViewData["Title"] - HarelTech WMS App</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" async />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet" async />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Righteous&display=swap" rel="stylesheet" async />
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Material Design Bootstrap -->
    <!--<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css" rel="stylesheet">-->
    <link href="~/lib/mdb/css/mdb.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdn.priority-software.com/upgrades/var/api/head/priorityapp.nocache.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@pwabuilder/pwaupdate"></script>
</head>

<body>
    <!-- preloader -->
    <div id="mdb-preloader" class="flex-center" style="opacity: 0.6;">
        <div class="preloader-wrapper active">
            <div class="spinner-layer spinner-blue-only" style="color: #3DBFD9 !important;">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
    </div>
    <!-- preloader -->

    @await Html.PartialAsync("_nav")

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--Modal: modalConfirm-->
    <div class="modal fade" id="modalConfirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm modal-notify modal-info" role="document">
            <!--Content-->
            <div class="modal-content text-center">
                <!--Header-->
                <div class="modal-header d-flex justify-content-center">
                    <p class="heading">Priority Message</p>
                </div>

                <!--Body-->
                <div class="modal-body">
                    <p id="p_message"></p>
                </div>

                <!--Footer-->
                <div class="modal-footer flex-center">
                    <a id="confirm_btn" type="button" class="btn  btn-info waves-effect" data-dismiss="modal">Ok</a>
                </div>
            </div>
            <!--/.Content-->
        </div>
    </div>
    <!--Modal: modalConfirm-->
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js"></script>-->
    <script type="text/javascript" src="~/lib/mdb/js/mdb.min.js"></script>
    <script type="text/javascript" src="~/lib/jquery-validation/dist/jquery.validate.min.js" defer></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js" defer></script>
    <script>
        $(window).on('load', function () {
            $('#mdb-preloader').hide();
        });
        $(document).ready(function () {
            // SideNav Button Initialization
            $(".navbar-toggler").sideNav();
            // SideNav Scrollbar Initialization
            var sideNavScrollbar = document.querySelector('.custom-scrollbar');
            var ps = new PerfectScrollbar(sideNavScrollbar);

            const el = document.createElement('pwa-update');
            document.body.appendChild(el);
        });


    </script>
    
    
    @RenderSection("Scripts", required: false)
</body>
</html>

HarelTech.WMS.App/Pages/Shared/_nav.cshtml
@using System.Security.Claims;
@{ 
    bool notShow = Context.Request.Path.ToString().Contains("Login") || Context.Request.Path.ToString().Contains("Company");
}
@if (User.Identity.IsAuthenticated)
{
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
                <button id="btn_menu" class="navbar-toggler collapse" type="button" data-activates="slide-out"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a href="#" id="btn_back" style="display: none"><i class="fas fa-chevron-left"></i></a>
                <span id="page_title" class="navbar-brand mx-auto">@ViewData["PageTitle"]</span>
            </div>
        </nav>
    </header>

    <!-- Sidebar navigation -->
    <div id="slide-out" class="side-nav fixed sn-bg-2" style="width: 0px !important;">
        <ul class="custom-scrollbar" style="font-weight: 700; font-size: 16px;">
            <!-- Logo -->
            <li>
                <div class="flex-center mt-5">
                    <i class="fa fa-user-circle fa-4x" aria-hidden="true" style="color: #3DBFD9;"></i>
                </div>
            </li>
            <li>
                <div class="flex-center">
                    <span>
                        @User.Claims.FirstOrDefault(w => w.Type == ClaimTypes.Name).Value
                    </span>
                </div>
            </li>
            <li><hr style="color: white !important;" /></li>
            <li>
                <a asp-page="/Account/Company" asp-page-handler="Companies" class="waves-effect text-white">Select Warehouse <i class="fas fa-chevron-right float-right mt-4 mr-4"></i></a>
            </li>
            @if(!notShow)
            {
            <li>
                <a asp-page="/Index" class="waves-effect text-white">Dashboard <i class="fas fa-chevron-right float-right mt-4 mr-4"></i></a>
            </li>
            <li>
                <a asp-page="/Tasks/Index" asp-route-taskType="1" class="waves-effect text-white">Pick <i class="fas fa-chevron-right float-right mt-4 mr-4"></i></a>
            </li>
            <li>
                <a asp-page="/Tasks/Index" asp-route-taskType="2" class="waves-effect text-white">Ship <i class="fas fa-chevron-right float-right mt-4 mr-4"></i></a>
            </li>
            <li>
                <a asp-page="/Tasks/Index" asp-route-taskType="3" class="waves-effect text-white">Receive <i class="fas fa-chevron-right float-right mt-4 mr-4"></i></a>
            </li>
            <li>
                <a asp-page="/Tasks/Index" asp-route-taskType="4" class="waves-effect text-white">Store <i class="fas fa-chevron-right float-right mt-4 mr-4"></i></a>
            </li>
            <li>
                <a asp-page="/Tasks/Index" asp-route-taskType="5" class="waves-effect text-white">Transfer <i class="fas fa-chevron-right float-right mt-4 mr-4"></i></a>
            </li>

            <li>
                <a asp-page="/Account/Login" asp-page-handler="Logout" class="waves-effect text-white">Exit <i class="fas fa-chevron-right float-right mt-4 mr-4"></i></a>
            </li>
            }
        </ul>
        <div class="sidenav-bg rgba-black-light"></div>
    </div>
}

HarelTech.WMS.App/Pages/Shared/_pages.cshtml
@page
<!--Modal: modalConfirm-->
<div class="modal fade" id="modalConfirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-sm modal-notify modal-info" role="document">
        <!--Content-->
        <div class="modal-content text-center">
            <!--Header-->
            <div class="modal-header d-flex justify-content-center">
                <p class="heading">Priority Message</p>
            </div>

            <!--Body-->
            <div class="modal-body">
                <p id="p_message"></p>
            </div>

            <!--Footer-->
            <div class="modal-footer flex-center">
                <a id="confirm_btn" type="button" class="btn  btn-info waves-effect" data-dismiss="modal">Ok</a>
            </div>
        </div>
        <!--/.Content-->
    </div>
</div>
<!--Modal: modalConfirm-->
<!--Modal: modalConfirmPartialCompleteTask-->
@await Html.PartialAsync("_modalConfirmPartialCompleteTask")
<!--Modal: modalConfirmCompleteTask-->
@await Html.PartialAsync("_modalConfirmCompleteTask")
<!-- Bins -->
@await Html.PartialAsync("_partialBins")